export const assetsToCache = [
  // --- コアファイル ---
  './',
  './index.html',
  './src/style.css',
  './src/soundPlayer.js',

  // --- JavaScriptファイル ---
  './src/config.js',
  './src/input_handler.js',
  './src/main.js',
  './src/player.js',
  './src/scaffold.js',
  './src/score_manager.js',
  './src/stage.js',
  './src/scenes/game_description.js',
  './src/scenes/game_over.js',
  './src/scenes/game.js',
  './src/scenes/instrument_select.js',
  './src/scenes/main.js',
  './src/scenes/ranking.js',
  './src/scenes/settings.js',
  './src/ui/button.js',
  './src/ui/scrollbar.js',
  './src/ui/volume_slider.js',

  // --- 画像ファイル ---
  './assets/img/character_jump.png',
  './assets/img/character_wait.png',
  './assets/img/character_woke.png',
  './assets/img/character_woke2.png',
  './assets/img/instrument_drum.png',
  './assets/img/scaffold.png',
  './assets/img/bg_game2.png',
  './assets/img/bg_gameover.png',
  './assets/img/gita.png',
  './assets/img/ground.png',
  './assets/img/tree.png',
  './assets/img/tree2.png',
  './assets/img/tree3.png',
  './assets/img/tree4.png',
  './assets/img/stump.png',
  './assets/img/logo.png',
  './assets/img/bg_game.png',
  './assets/img/instrument_piano.png',
  './assets/img/instrument_taiko.png',
  './assets/img/instrument_tambourine.png',
  './assets/img/enemy.png',
  './assets/img/bg_title.png',
  './assets/img/instrument_triangle.png',

  // --- サウンドファイル ---
  './assets/sound/drum/track01.wav',
  './assets/sound/drum/track02.wav',
  './assets/sound/drum/track03.wav',
  './assets/sound/drum/track04.wav',
  './assets/sound/drum/track05.wav',
  './assets/sound/drum/track06.wav',
  './assets/sound/game/click.wav',
  './assets/sound/game/game_bgm.wav',
  './assets/sound/game/gameover_bgm.wav',
  './assets/sound/game/home_bgm.wav',
  './assets/sound/game/jump.wav',
  './assets/sound/game/tree_fall.wav',
  './assets/sound/guitar/track01.wav',
  './assets/sound/guitar/track02.wav',
  './assets/sound/guitar/track03.wav',
  './assets/sound/guitar/track04.wav',
  './assets/sound/piano/track01.wav',
  './assets/sound/piano/track02.wav',
  './assets/sound/piano/track03.wav',
  './assets/sound/piano/track04.wav',
  './assets/sound/piano/track05.wav',
  './assets/sound/piano/track06.wav',
  './assets/sound/piano/track07.wav',
  './assets/sound/taiko/track01.wav',
  './assets/sound/taiko/track02.wav',
  './assets/sound/taiko/track03.wav',
  './assets/sound/tambourie/track01.wav',
  './assets/sound/tambourie/track02.wav',
  './assets/sound/triangle/track01.wav',
];
